package com.ccp.aop;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks the {@code toString()} introduced by {@code CcpToStringAspect}.
 * <p>
 * After weaving, the introduced method cannot be told apart from a hand-written one (it is neither synthetic nor a
 * bridge). This annotation is what lets {@code CcpToStringBuilder}, when serializing an attribute, know whether the
 * {@code toString()} of that type is the type's own (and must therefore be used as text) or was generated by the
 * aspect (and the object must therefore be expanded as nested JSON instead of being embedded as an escaped string).
 * <p>
 * Not meant to be used by hand.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface CcpGeneratedToString {

}
