package com.ccp.aop;

import java.lang.reflect.Array;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Collection;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.lang.reflect.Method;

/**
 * Builds the JSON representation used by the {@code toString()} that the
 * {@code CcpToStringAspect} introduces into classes that do not implement the method.
 *
 * Rules:
 * <ul>
 *   <li>If the class (and its superclasses) declares no instance attribute,
 *       the result is the class name, not a JSON.</li>
 *   <li>Otherwise, the result is the JSON with the object's instance attributes.</li>
 * </ul>
 *
 * This builder <b>never throws an exception</b>: {@code toString()} is called in logs, error
 * messages and debuggers, where a failure would mask the original problem. Any unexpected
 * error degrades to the class name with the identity hash.
 *
 * Circular references and very deep graphs are cut off to avoid
 * {@code StackOverflowError}.
 */
public final class CcpToStringBuilder {

	/**
	 * Maximum nesting depth before summarizing the object by its class name.
	 */
	private static final int MAX_DEPTH = 6;

	/**
	 * Objects being serialized in the current thread, to detect circular references.
	 * IdentityHashMap because the comparison must be by reference: calling equals/hashCode
	 * of an arbitrary object during toString could recurse or fail.
	 */
	private static final ThreadLocal<IdentityHashMap<Object, Object>> IN_PROGRESS =
			ThreadLocal.withInitial(IdentityHashMap::new);

	/**
	 * Cache of the instance attributes per class: the reflective scan of the hierarchy
	 * is done only once per class.
	 */
	private static final Map<Class<?>, List<Field>> FIELDS_CACHE = new ConcurrentHashMap<>();

	private CcpToStringBuilder() {
	}

	/**
	 * Entry point called by the {@code toString()} introduced by the aspect.
	 */
	public static String build(Object object) {
		boolean isNull = object == null;
		if (isNull) {
			return "null";
		}
		try {
			var objectClass = object.getClass();
			List<Field> fields = getInstanceFields(objectClass);
			boolean fieldsEmpty = fields.isEmpty();
			if (fieldsEmpty) {
				var classWithoutFields = object.getClass();
				var className = classWithoutFields.getName();
				return className;
			}
			String objectJson = writeObject(object, fields, 0);
			return objectJson;
		} catch (Throwable t) {
			String identity = identityOf(object);
			return identity;
		}
	}

	/**
	 * Instance attributes declared in the class and in its superclasses (except Object).
	 * Static and synthetic ones are left out: the former are class state, not object state,
	 * and the latter are generated by the compiler or by instrumentation (this$0, $jacocoData).
	 */
	private static List<Field> getInstanceFields(Class<?> clazz) {
		List<Field> instanceFields = FIELDS_CACHE.computeIfAbsent(clazz, key -> {
			List<Field> fields = new ArrayList<>();
			for (Class<?> current = key; current != null && current != Object.class; current = current.getSuperclass()) {
				Field[] declaredFields = current.getDeclaredFields();
				for (Field field : declaredFields) {
					boolean synthetic = field.isSynthetic();
					boolean isSyntheticOrStatic = synthetic || Modifier.isStatic(field.getModifiers());
					if (isSyntheticOrStatic) {
						continue;
					}
					try {
						field.setAccessible(true);
					} catch (RuntimeException e) {
						continue;
					}
					fields.add(field);
				}
			}
			return fields;
		});
		return instanceFields;
	}

	private static String writeObject(Object object, List<Field> fields, int depth) {
		IdentityHashMap<Object, Object> inProgress = IN_PROGRESS.get();
		boolean containsKey = inProgress.containsKey(object);
		if (containsKey) {
			var objectClass = object.getClass();
			var objectClassName = objectClass.getName();
			String circularReferenceStart = "<circular reference: " + objectClassName;
			String circularReferenceText = circularReferenceStart + ">";
			String quotedText = quote(circularReferenceText);
			return quotedText;
		}
		inProgress.put(object, object);
		try {
			StringBuilder sb = new StringBuilder("{");
			boolean first = true;
			for (Field field : fields) {
				Object value;
				try {
					value = field.get(object);
				} catch (IllegalAccessException | RuntimeException e) {
					continue;
				}
				boolean notFirst = first == false;
				if (notFirst) {
					sb.append(",");
				}
				first = false;
				String fieldName = field.getName();
				String quotedFieldName = quote(fieldName);
				StringBuilder sbWithFieldName = sb.append(quotedFieldName);
				StringBuilder sbWithColon = sbWithFieldName.append(":");
				int nextDepth = depth + 1;
				String valueJson = writeValue(value, nextDepth);
				sbWithColon.append(valueJson);
			}
			StringBuilder closedSb = sb.append("}");
			String objectJson = closedSb.toString();
			return objectJson;
		} finally {
			inProgress.remove(object);
			boolean inProgressEmpty = inProgress.isEmpty();
			if (inProgressEmpty) {
				IN_PROGRESS.remove();
			}
		}
	}

	private static String writeValue(Object value, int depth) {
		boolean isNull = value == null;
		if (isNull) {
			return "null";
		}
		boolean isBoolean = value instanceof Boolean;
		if (isBoolean) {
			String booleanText = value.toString();
			return booleanText;
		}
		boolean isNumber = value instanceof Number;
		if (isNumber) {
			Number number = (Number) value;
			String numberJson = writeNumber(number);
			return numberJson;
		}
		boolean isCharSequence = value instanceof CharSequence;
		boolean isText = isCharSequence || value instanceof Character;
		if (isText) {
			String text = value.toString();
			String quotedText = quote(text);
			return quotedText;
		}
		boolean isEnum = value instanceof Enum;
		if (isEnum) {
			Enum<?> enumValue = (Enum<?>) value;
			String valueName = (enumValue).name();
			String quotedText = quote(valueName);
			return quotedText;
		}
		boolean isTooDeep = depth > MAX_DEPTH;
		if (isTooDeep) {
			var valueClass = value.getClass();
			String valueClassName = valueClass.getName();
			String quotedText = quote(valueClassName);
			return quotedText;
		}
		var valueTypeForArrayCheck = value.getClass();
		var isArray = valueTypeForArrayCheck.isArray();
		if (isArray) {
			String arrayJson = writeArray(value, depth);
			return arrayJson;
		}
		boolean isCollection = value instanceof Collection;
		if (isCollection) {
			Collection<?> collection = (Collection<?>) value;
			String collectionJson = writeCollection(collection, depth);
			return collectionJson;
		}
		boolean isMap = value instanceof Map;
		if (isMap) {
			Map<?, ?> map = (Map<?, ?>) value;
			String mapJson = writeMap(map, depth);
			return mapJson;
		}
		var valueTypeForToStringCheck = value.getClass();
		boolean ownToString = hasOwnToString(valueTypeForToStringCheck);
		// If the type has its own toString, it is the best representation available: use its
		// text. Covers dates, UUID, BigDecimal and any class with a custom toString.
		if (ownToString) {
			String valueText = String.valueOf(value);
			String quotedText = quote(valueText);
			return quotedText;
		}
		var valueTypeForFields = value.getClass();
		List<Field> fields = getInstanceFields(valueTypeForFields);
		boolean fieldsEmpty = fields.isEmpty();
		if (fieldsEmpty) {
			var valueTypeWithoutFields = value.getClass();
			String valueTypeName = valueTypeWithoutFields.getName();
			String quotedText = quote(valueTypeName);
			return quotedText;
		}
		String objectJson = writeObject(value, fields, depth);
		return objectJson;
	}

	/**
	 * Tells whether the type's toString was written by hand rather than generated by the aspect.
	 *
	 * The first declaration found going up the hierarchy is the one that counts, since it is the one
	 * the object actually executes. If it has {@code @CcpGeneratedToString}, the toString is this
	 * builder's: in that case the object is expanded as nested JSON instead of becoming a string
	 * with escaped JSON inside.
	 */
	private static boolean hasOwnToString(Class<?> clazz) {
		for (Class<?> current = clazz; current != null && current != Object.class; current = current.getSuperclass()) {
			try {
				Method declaredMethod = current.getDeclaredMethod("toString");
				var annotationPresent = declaredMethod
						.isAnnotationPresent(CcpGeneratedToString.class);
						boolean isHandWritten = annotationPresent == false;
						return isHandWritten;
			} catch (NoSuchMethodException e) {
				continue;
			} catch (RuntimeException e) {
				return true;
			}
		}
		return false;
	}

	private static String writeNumber(Number number) {
		double asDouble = number.doubleValue();
		boolean isNaN = Double.isNaN(asDouble);
		boolean isNotFinite = isNaN || Double.isInfinite(asDouble);
		// JSON represents neither NaN nor infinity: these values become text.
		if (isNotFinite) {
			String numberText = number.toString();
			String quotedText = quote(numberText);
			return quotedText;
		}
		String numberText = number.toString();
		return numberText;
	}

	private static String writeArray(Object array, int depth) {
		IdentityHashMap<Object, Object> inProgress = IN_PROGRESS.get();
		boolean containsKey = inProgress.containsKey(array);
		if (containsKey) {
			var arrayClass = array.getClass();
			var arrayClassName = arrayClass.getName();
			String circularReferenceStart = "<circular reference: " + arrayClassName;
			String circularReferenceText = circularReferenceStart + ">";
			String quotedText = quote(circularReferenceText);
			return quotedText;
		}
		inProgress.put(array, array);
		try {
			StringBuilder sb = new StringBuilder("[");
			int length = Array.getLength(array);
			for (int i = 0; i < length; i++) {
				boolean notFirst = i > 0;
				if (notFirst) {
					sb.append(",");
				}
				var item = Array.get(array, i);
				int nextDepth = depth + 1;
				String valueJson = writeValue(item, nextDepth);
				sb.append(valueJson);
			}
			StringBuilder closedSb = sb.append("]");
			String arrayJson = closedSb.toString();
			return arrayJson;
		} finally {
			inProgress.remove(array);
		}
	}

	private static String writeCollection(Collection<?> collection, int depth) {
		IdentityHashMap<Object, Object> inProgress = IN_PROGRESS.get();
		boolean containsKey = inProgress.containsKey(collection);
		if (containsKey) {
			var collectionClass = collection.getClass();
			var collectionClassName = collectionClass.getName();
			String circularReferenceStart = "<circular reference: " + collectionClassName;
			String circularReferenceText = circularReferenceStart + ">";
			String quotedText = quote(circularReferenceText);
			return quotedText;
		}
		inProgress.put(collection, collection);
		try {
			StringBuilder sb = new StringBuilder("[");
			boolean first = true;
			for (Object item : collection) {
				boolean notFirst = first == false;
				if (notFirst) {
					sb.append(",");
				}
				first = false;
				int nextDepth = depth + 1;
				String valueJson = writeValue(item, nextDepth);
				sb.append(valueJson);
			}
			StringBuilder closedSb = sb.append("]");
			String collectionJson = closedSb.toString();
			return collectionJson;
		} catch (RuntimeException e) {
			String identity = identityOf(collection);
			String quotedText = quote(identity);
			return quotedText;
		} finally {
			inProgress.remove(collection);
		}
	}

	private static String writeMap(Map<?, ?> map, int depth) {
		IdentityHashMap<Object, Object> inProgress = IN_PROGRESS.get();
		boolean containsKey = inProgress.containsKey(map);
		if (containsKey) {
			var mapClass = map.getClass();
			var mapClassName = mapClass.getName();
			String circularReferenceStart = "<circular reference: " + mapClassName;
			String circularReferenceText = circularReferenceStart + ">";
			String quotedText = quote(circularReferenceText);
			return quotedText;
		}
		inProgress.put(map, map);
		try {
			StringBuilder sb = new StringBuilder("{");
			boolean first = true;
			var entrySet = map.entrySet();
			for (Map.Entry<?, ?> entry : entrySet) {
				boolean notFirst = first == false;
				if (notFirst) {
					sb.append(",");
				}
				first = false;
				var entryKey = entry.getKey();
				String keyText = String.valueOf(entryKey);
				String quotedKey = quote(keyText);
				StringBuilder sbWithKey = sb.append(quotedKey);
				StringBuilder sbWithColon = sbWithKey.append(":");
				var entryValue = entry.getValue();
				int nextDepth = depth + 1;
				String valueJson = writeValue(entryValue, nextDepth);
				sbWithColon
						.append(valueJson);
			}
			StringBuilder closedSb = sb.append("}");
			String mapJson = closedSb.toString();
			return mapJson;
		} catch (RuntimeException e) {
			String identity = identityOf(map);
			String quotedText = quote(identity);
			return quotedText;
		} finally {
			inProgress.remove(map);
		}
	}

	private static String identityOf(Object object) {
		var objectClass = object.getClass();
		var objectClassName = objectClass.getName();
		var classNameWithAt = objectClassName + "@";
		int identityHashCode = System.identityHashCode(object);
		String toHexString = Integer.toHexString(identityHashCode);
		var identity = classNameWithAt + toHexString;
		return identity;
	}

	private static String quote(String text) {
		int textLength = text.length();
		int capacity = textLength + 2;
		StringBuilder stringBuilder = new StringBuilder(capacity);
		StringBuilder sb = stringBuilder.append('"');
		for (int i = 0; i < text.length(); i++) {
			char c = text.charAt(i);
			switch (c) {
			case '"':
				sb.append("\\\"");
				break;
			case '\\':
				sb.append("\\\\");
				break;
			case '\n':
				sb.append("\\n");
				break;
			case '\r':
				sb.append("\\r");
				break;
			case '\t':
				sb.append("\\t");
				break;
			case '\b':
				sb.append("\\b");
				break;
			case '\f':
				sb.append("\\f");
				break;
			default:
				if (c < 0x20) {
					int codePoint = (int) c;
					String stringFormat = String.format("\\u%04x", codePoint);
					sb.append(stringFormat);
				} else {
					sb.append(c);
				}
			}
		}
		StringBuilder closedSb = sb.append('"');
		String quotedText = closedSb.toString();
		return quotedText;
	}
}
